export const frota = [
	{
		nome: 'COMPACTO',
		codigoLocaliza: 'A',
		codigoInternacional: 'ECMN',
		codigoTipoGrupoVeiculo: 1,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/NUNS.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 1,
			quantidadeMalasPequenas: 1,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_000734',
				codigoAcronymLocaliza: 'NUNS',
				codigoModelo: '000734',
				codigoFabricante: 'A',
				nome: 'Fiat Uno 1.0',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/NUNS.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'COMPACTO COM AR',
		codigoLocaliza: 'B',
		codigoInternacional: 'ECMR',
		codigoTipoGrupoVeiculo: 1,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/KWID.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 1,
			quantidadeMalasPequenas: 1,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'R_000384',
				codigoAcronymLocaliza: 'KWID',
				codigoModelo: '000384',
				codigoFabricante: 'R',
				nome: 'Renault Kwid 1.0',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/KWID.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001072',
				codigoAcronymLocaliza: 'MOBI',
				codigoModelo: '001072',
				codigoFabricante: 'A',
				nome: 'Fiat Mobi 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/MOBI.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001135',
				codigoAcronymLocaliza: 'NUNB',
				codigoModelo: '001135',
				codigoFabricante: 'A',
				nome: 'Fiat Uno 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/NUNB.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'ECONÔMICO COM AR',
		codigoLocaliza: 'C',
		codigoInternacional: 'EDMR',
		codigoTipoGrupoVeiculo: 1,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/GOLC.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 1,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'B_000868',
				codigoAcronymLocaliza: 'GOLC',
				codigoModelo: '000868',
				codigoFabricante: 'B',
				nome: 'VW Gol 1.0',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/GOLC.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000473',
				codigoAcronymLocaliza: 'KACR',
				codigoModelo: '000473',
				codigoFabricante: 'D',
				nome: 'Novo Ford Ka 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/KACR.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000190',
				codigoAcronymLocaliza: 'SANX',
				codigoModelo: '000190',
				codigoFabricante: 'R',
				nome: 'Renault Sandero 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/SANX.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000985',
				codigoAcronymLocaliza: 'ONIC',
				codigoModelo: '000985',
				codigoFabricante: 'C',
				nome: 'GM Onix Joy 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ONIC.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'ECONÔMICO C/ AR FAST',
		codigoLocaliza: 'CK',
		codigoInternacional: 'HDMR',
		codigoTipoGrupoVeiculo: 15,
		categoria: 'Fast',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/ONXF.png',
		acessorios: [
			{
				descricao: 'Abre no App',
				codigoAcessorio: 34,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 1,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'C_000945',
				codigoAcronymLocaliza: 'ONXF',
				codigoModelo: '000945',
				codigoFabricante: 'C',
				nome: 'GM Onix 1.0 FAST',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ONXF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001141',
				codigoAcronymLocaliza: 'ARGF',
				codigoModelo: '001141',
				codigoFabricante: 'A',
				nome: 'FIAT Argo 1.0 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ARGF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000561',
				codigoAcronymLocaliza: 'KAHF',
				codigoModelo: '000561',
				codigoFabricante: 'D',
				nome: 'Ford Ka Hatch 1.0 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/KAHF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000892',
				codigoAcronymLocaliza: 'POLF',
				codigoModelo: '000892',
				codigoFabricante: 'B',
				nome: 'VW Polo 1.0 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/POLF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'O_000212',
				codigoAcronymLocaliza: 'PEUF',
				codigoModelo: '000212',
				codigoFabricante: 'O',
				nome: 'Peugeot 208 Active 1.2 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PEUF.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000184',
				codigoAcronymLocaliza: 'HB1F',
				codigoModelo: '000184',
				codigoFabricante: '1',
				nome: 'Hyundai HB20 1.0 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/HB1F.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000435',
				codigoAcronymLocaliza: 'SADF',
				codigoModelo: '000435',
				codigoFabricante: 'R',
				nome: 'Renault Sandero 1.0 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/SADF.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'ECONÔMICO ESPECIAL C/AR',
		codigoLocaliza: 'CE',
		codigoInternacional: 'HCMR',
		codigoTipoGrupoVeiculo: 1,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/ARGO.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 1,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_001132',
				codigoAcronymLocaliza: 'ARGO',
				codigoModelo: '001132',
				codigoFabricante: 'A',
				nome: 'Fiat Argo 1.0',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ARGO.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000780',
				codigoAcronymLocaliza: 'ONIX',
				codigoModelo: '000780',
				codigoFabricante: 'C',
				nome: 'GM Onix LT 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ONIX.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000850',
				codigoAcronymLocaliza: 'POLA',
				codigoModelo: '000850',
				codigoFabricante: 'B',
				nome: 'VW Polo 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/POLA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'O_000193',
				codigoAcronymLocaliza: 'PEUC',
				codigoModelo: '000193',
				codigoFabricante: 'O',
				nome: 'Peugeot 208 1.2',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PEUC.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000197',
				codigoAcronymLocaliza: 'HB2X',
				codigoModelo: '000197',
				codigoFabricante: '1',
				nome: 'Hyundai HB20 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/HB2X.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'T_000130',
				codigoAcronymLocaliza: 'CTC3',
				codigoModelo: '000130',
				codigoFabricante: 'T',
				nome: 'Citroen C3 1.2',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CTC3.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'ECONÔMICO SEDAN C/AR',
		codigoLocaliza: 'CS',
		codigoInternacional: 'EXMR',
		codigoTipoGrupoVeiculo: 1,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/ONIT.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'C_000967',
				codigoAcronymLocaliza: 'ONIT',
				codigoModelo: '000967',
				codigoFabricante: 'C',
				nome: 'GM Onix 1.0',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ONIT.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000178',
				codigoAcronymLocaliza: 'HB2C',
				codigoModelo: '000178',
				codigoFabricante: '1',
				nome: 'Hyundai HB20S 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/HB2C.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000297',
				codigoAcronymLocaliza: 'LOGN',
				codigoModelo: '000297',
				codigoFabricante: 'R',
				nome: 'Renault Logan 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/LOGN.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000478',
				codigoAcronymLocaliza: 'KAS1',
				codigoModelo: '000478',
				codigoFabricante: 'D',
				nome: 'Ford Ka Sedan 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/KAS1.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000866',
				codigoAcronymLocaliza: 'VOYE',
				codigoModelo: '000866',
				codigoFabricante: 'B',
				nome: 'VW Voyage 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VOYE.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'U_000133',
				codigoAcronymLocaliza: 'VESX',
				codigoModelo: '000133',
				codigoFabricante: 'U',
				nome: 'Nissan Versa 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VESX.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000858',
				codigoAcronymLocaliza: 'PRIC',
				codigoModelo: '000858',
				codigoFabricante: 'C',
				nome: 'GM Prisma 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PRIC.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001092',
				codigoAcronymLocaliza: 'GRSX',
				codigoModelo: '001092',
				codigoFabricante: 'A',
				nome: 'Fiat Grand Siena 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/GRSX.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'INTERMEDIÁRIO',
		codigoLocaliza: 'F',
		codigoInternacional: 'SDMR',
		codigoTipoGrupoVeiculo: 3,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/GOLL.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
			{
				descricao: 'Motor 1.6',
				codigoAcessorio: 17,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'B_000734',
				codigoAcronymLocaliza: 'GOLL',
				codigoModelo: '000734',
				codigoFabricante: 'B',
				nome: 'VW Gol 1.6',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/GOLL.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000203',
				codigoAcronymLocaliza: 'HB20',
				codigoModelo: '000203',
				codigoFabricante: '1',
				nome: 'Hyundai HB20 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/HB20.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000196',
				codigoAcronymLocaliza: 'SAND',
				codigoModelo: '000196',
				codigoFabricante: 'R',
				nome: 'Renault Sandero 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/SAND.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'INTERMEDIÁRIO SEDAN',
		codigoLocaliza: 'FS',
		codigoInternacional: 'SXMR',
		codigoTipoGrupoVeiculo: 3,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/CROX.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Motor 1.6',
				codigoAcessorio: 17,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_001122',
				codigoAcronymLocaliza: 'CROX',
				codigoModelo: '001122',
				codigoFabricante: 'A',
				nome: 'Fiat Cronos 1.3',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CROX.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000857',
				codigoAcronymLocaliza: 'VIRM',
				codigoModelo: '000857',
				codigoFabricante: 'B',
				nome: 'VW Virtus 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VIRM.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000962',
				codigoAcronymLocaliza: 'ONIS',
				codigoModelo: '000962',
				codigoFabricante: 'C',
				nome: 'GM Onix 1.0 Turbo',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ONIS.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000131',
				codigoAcronymLocaliza: 'HB2S',
				codigoModelo: '000131',
				codigoFabricante: '1',
				nome: 'Hyundai HB20S 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/HB2S.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000239',
				codigoAcronymLocaliza: 'LOGA',
				codigoModelo: '000239',
				codigoFabricante: 'R',
				nome: 'Renault Logan 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/LOGA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000481',
				codigoAcronymLocaliza: 'KASE',
				codigoModelo: '000481',
				codigoFabricante: 'D',
				nome: 'Ford Ka Sedan 1.5',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/KASE.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000488',
				codigoAcronymLocaliza: 'VOYA',
				codigoModelo: '000488',
				codigoFabricante: 'B',
				nome: 'VW Voyage 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VOYA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'U_000135',
				codigoAcronymLocaliza: 'VESS',
				codigoModelo: '000135',
				codigoFabricante: 'U',
				nome: 'Nissan Versa 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VESS.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001171',
				codigoAcronymLocaliza: 'GSEN',
				codigoModelo: '001171',
				codigoFabricante: 'A',
				nome: 'Fiat Grand Siena 1.4',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/GSEN.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000805',
				codigoAcronymLocaliza: 'PRIS',
				codigoModelo: '000805',
				codigoFabricante: 'C',
				nome: 'GM Prisma 1.4',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PRIS.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'INTERMEDIÁRIO FAST',
		codigoLocaliza: 'FK',
		codigoInternacional: 'RDMR',
		codigoTipoGrupoVeiculo: 15,
		categoria: 'Fast',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/KASF.png',
		acessorios: [
			{
				descricao: 'Abre no App',
				codigoAcessorio: 34,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'D_000542',
				codigoAcronymLocaliza: 'KASF',
				codigoModelo: '000542',
				codigoFabricante: 'D',
				nome: 'Ford Ka Sedan 1.5 FAST',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/KASF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000893',
				codigoAcronymLocaliza: 'VITF',
				codigoModelo: '000893',
				codigoFabricante: 'B',
				nome: 'VW Virtus 1.6 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VITF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000432',
				codigoAcronymLocaliza: 'LOGF',
				codigoModelo: '000432',
				codigoFabricante: 'R',
				nome: 'Renault Logan 1.6 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/LOGF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'U_000193',
				codigoAcronymLocaliza: 'VEFF',
				codigoModelo: '000193',
				codigoFabricante: 'U',
				nome: 'Nissan Versa FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VEFF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001167',
				codigoAcronymLocaliza: 'CRNF',
				codigoModelo: '001167',
				codigoFabricante: 'A',
				nome: 'Fiat Cronos 1.3 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CRNF.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'INTERMEDIÁRIO AUTOMÁTICO',
		codigoLocaliza: 'FX',
		codigoInternacional: 'SDAR',
		codigoTipoGrupoVeiculo: 3,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/PEUA.png',
		acessorios: [
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Motor 1.6',
				codigoAcessorio: 17,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 1,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'O_000195',
				codigoAcronymLocaliza: 'PEUA',
				codigoModelo: '000195',
				codigoFabricante: 'O',
				nome: 'Peugeot 208 1.6',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PEUA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000858',
				codigoAcronymLocaliza: 'VIRT',
				codigoModelo: '000858',
				codigoFabricante: 'B',
				nome: 'VW Virtus Comfortline',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VIRT.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001125',
				codigoAcronymLocaliza: 'CRON',
				codigoModelo: '001125',
				codigoFabricante: 'A',
				nome: 'Fiat Cronos 1.8',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CRON.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000964',
				codigoAcronymLocaliza: 'ONAT',
				codigoModelo: '000964',
				codigoFabricante: 'C',
				nome: 'GM Onix Plus 1.0 Turbo',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ONAT.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000132',
				codigoAcronymLocaliza: 'HB2A',
				codigoModelo: '000132',
				codigoFabricante: '1',
				nome: 'Hyundai HB20S',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/HB2A.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000204',
				codigoAcronymLocaliza: 'HB2H',
				codigoModelo: '000204',
				codigoFabricante: '1',
				nome: 'Hyundai HB20 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/HB2H.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'U_000143',
				codigoAcronymLocaliza: 'VESF',
				codigoModelo: '000143',
				codigoFabricante: 'U',
				nome: 'Nissan Versa 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VESF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000772',
				codigoAcronymLocaliza: 'COTZ',
				codigoModelo: '000772',
				codigoFabricante: 'C',
				nome: 'GM Cobalt 1.8',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/COTZ.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'G_000211',
				codigoAcronymLocaliza: 'ETIA',
				codigoModelo: '000211',
				codigoFabricante: 'G',
				nome: 'Toyota Etios 1.5',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ETIA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000447',
				codigoAcronymLocaliza: 'LOGU',
				codigoModelo: '000447',
				codigoFabricante: 'R',
				nome: 'Renault Logan 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/LOGU.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000425',
				codigoAcronymLocaliza: 'SANA',
				codigoModelo: '000425',
				codigoFabricante: 'R',
				nome: 'Renault Sandero 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/SANA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'G_000309',
				codigoAcronymLocaliza: 'YARS',
				codigoModelo: '000309',
				codigoFabricante: 'G',
				nome: 'Toyota Yaris 1.5',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/YARS.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'INTERMEDIÁRIO AUT. FAST',
		codigoLocaliza: 'FW',
		codigoInternacional: 'RDAR',
		codigoTipoGrupoVeiculo: 15,
		categoria: 'Fast',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/VIRF.png',
		acessorios: [
			{
				descricao: 'Abre no App',
				codigoAcessorio: 34,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'B_000875',
				codigoAcronymLocaliza: 'VIRF',
				codigoModelo: '000875',
				codigoFabricante: 'B',
				nome: 'VW Virtus Comfortline FAST',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/VIRF.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000144',
				codigoAcronymLocaliza: 'HB2F',
				codigoModelo: '000144',
				codigoFabricante: '1',
				nome: 'Hyundai HB20S 1.6 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/HB2F.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000574',
				codigoAcronymLocaliza: 'ECSF',
				codigoModelo: '000574',
				codigoFabricante: 'D',
				nome: 'Ford Ecosport 1.5 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ECSF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'G_000226',
				codigoAcronymLocaliza: 'ETIF',
				codigoModelo: '000226',
				codigoFabricante: 'G',
				nome: 'Toyota Etios 1.5 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ETIF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'T_000152',
				codigoAcronymLocaliza: 'CACF',
				codigoModelo: '000152',
				codigoFabricante: 'T',
				nome: 'Citroen C4 Cactus 1.6 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CACF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'U_000180',
				codigoAcronymLocaliza: 'KICF',
				codigoModelo: '000180',
				codigoFabricante: 'U',
				nome: 'Nissan Kicks 1.6 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/KICF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000412',
				codigoAcronymLocaliza: 'DUTF',
				codigoModelo: '000412',
				codigoFabricante: 'R',
				nome: 'Renault Duster FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/DUTF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000944',
				codigoAcronymLocaliza: 'NIVF',
				codigoModelo: '000944',
				codigoFabricante: 'B',
				nome: 'VW Nivus 1.0 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/NIVF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001166',
				codigoAcronymLocaliza: 'CROF',
				codigoModelo: '001166',
				codigoFabricante: 'A',
				nome: 'Fiat Cronos 1.8 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CROF.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'ADAPTADO PESSOA C/ DEFICIÊNCIA',
		codigoLocaliza: 'FA',
		codigoInternacional: 'SXAR',
		codigoTipoGrupoVeiculo: 17,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/ONAD.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
			{
				descricao: 'Acelerador e freio manual',
				codigoAcessorio: 35,
			},
			{
				descricao: 'Inversor de Pedal Acelerador',
				codigoAcessorio: 36,
			},
			{
				descricao: 'Pomo giratório removível',
				codigoAcessorio: 37,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 5,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'C_001012',
				codigoAcronymLocaliza: 'ONAD',
				codigoModelo: '001012',
				codigoFabricante: 'C',
				nome: 'GM Onix 1.0 Turbo ADAPTADO',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ONAD.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001198',
				codigoAcronymLocaliza: 'CROA',
				codigoModelo: '001198',
				codigoFabricante: 'A',
				nome: 'Fiat Cronos 1.8 ADAPTADO',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CROA.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV',
		codigoLocaliza: 'G',
		codigoInternacional: 'IFMR',
		codigoTipoGrupoVeiculo: 7,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/DUST.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'R_000249',
				codigoAcronymLocaliza: 'DUST',
				codigoModelo: '000249',
				codigoFabricante: 'R',
				nome: 'Renault Duster  1.6',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/DUST.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000552',
				codigoAcronymLocaliza: 'ECOX',
				codigoModelo: '000552',
				codigoFabricante: 'D',
				nome: 'Ford Ecosport 1.5',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ECOX.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV COMPACTO AUTOMÁTICO',
		codigoLocaliza: 'GC',
		codigoInternacional: 'IDAR',
		codigoTipoGrupoVeiculo: 7,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/CACT.png',
		acessorios: [
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'T_000161',
				codigoAcronymLocaliza: 'CACT',
				codigoModelo: '000161',
				codigoFabricante: 'T',
				nome: 'Citroen C4 Cactus 1.6',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CACT.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000933',
				codigoAcronymLocaliza: 'NIVU',
				codigoModelo: '000933',
				codigoFabricante: 'B',
				nome: 'VW Nivus 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/NIVU.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001195',
				codigoAcronymLocaliza: 'PLSE',
				codigoModelo: '001195',
				codigoFabricante: 'A',
				nome: 'Fiat Pulse 1.0 Turbo',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PLSE.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'H_000018',
				codigoAcronymLocaliza: 'TIGG',
				codigoModelo: '000018',
				codigoFabricante: 'H',
				nome: 'Chery Tiggo 3X 1.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TIGG.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000382',
				codigoAcronymLocaliza: 'CAPR',
				codigoModelo: '000382',
				codigoFabricante: 'R',
				nome: 'Renault Nova Captur 1.3 Turbo',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CAPR.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'O_000228',
				codigoAcronymLocaliza: 'PEU2',
				codigoModelo: '000228',
				codigoFabricante: 'O',
				nome: 'Peugeot 2008 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PEU2.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'U_000163',
				codigoAcronymLocaliza: 'KICK',
				codigoModelo: '000163',
				codigoFabricante: 'U',
				nome: 'Nissan Kicks 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/KICK.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000380',
				codigoAcronymLocaliza: 'DUAT',
				codigoModelo: '000380',
				codigoFabricante: 'R',
				nome: 'Renault Duster 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/DUAT.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000553',
				codigoAcronymLocaliza: 'ECOT',
				codigoModelo: '000553',
				codigoFabricante: 'D',
				nome: 'Ford Ecosport 1.5',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ECOT.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV AUTOMÁTICO',
		codigoLocaliza: 'GX',
		codigoInternacional: 'IFAR',
		codigoTipoGrupoVeiculo: 7,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/RENE.png',
		acessorios: [
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: '8_000020',
				codigoAcronymLocaliza: 'RENE',
				codigoModelo: '000020',
				codigoFabricante: '8',
				nome: 'Jeep Renegade Sport 1.8',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/RENE.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000889',
				codigoAcronymLocaliza: 'TCRO',
				codigoModelo: '000889',
				codigoFabricante: 'B',
				nome: 'VW T-Cross 1.4 TSI',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TCRO.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000908',
				codigoAcronymLocaliza: 'TRAT',
				codigoModelo: '000908',
				codigoFabricante: 'C',
				nome: 'GM Tracker 1.4 Turbo',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TRAT.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000488',
				codigoAcronymLocaliza: 'ECOA',
				codigoModelo: '000488',
				codigoFabricante: 'D',
				nome: 'Ford EcoSport 2.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ECOA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000377',
				codigoAcronymLocaliza: 'CAPU',
				codigoModelo: '000377',
				codigoFabricante: 'R',
				nome: 'Renault Nova Captur 2.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CAPU.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV AUT. FAST',
		codigoLocaliza: 'GW',
		codigoInternacional: 'JFAR',
		codigoTipoGrupoVeiculo: 15,
		categoria: 'Fast',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/TCRF.png',
		acessorios: [
			{
				descricao: 'Abre no App',
				codigoAcessorio: 34,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'B_000900',
				codigoAcronymLocaliza: 'TCRF',
				codigoModelo: '000900',
				codigoFabricante: 'B',
				nome: 'VW T-Cross 1.4 TSI',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TCRF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000433',
				codigoAcronymLocaliza: 'CPFF',
				codigoModelo: '000433',
				codigoFabricante: 'R',
				nome: 'Renault Captur 2.0 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CPFF.png',
			},
			{
				blindado: false,
				codigoLocaliza: '8_000057',
				codigoAcronymLocaliza: 'RENF',
				codigoModelo: '000057',
				codigoFabricante: '8',
				nome: 'Jeep Renegade 1.8 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/RENF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000597',
				codigoAcronymLocaliza: 'ECOW',
				codigoModelo: '000597',
				codigoFabricante: 'D',
				nome: 'Ford Ecosport 2.0 FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ECOW.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'EXECUTIVO',
		codigoLocaliza: 'L',
		codigoInternacional: 'FDAR',
		codigoTipoGrupoVeiculo: 6,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/CORO.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'G_000120',
				codigoAcronymLocaliza: 'CORO',
				codigoModelo: '000120',
				codigoFabricante: 'G',
				nome: 'Toyota Corolla GLI',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CORO.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000828',
				codigoAcronymLocaliza: 'JETA',
				codigoModelo: '000828',
				codigoFabricante: 'B',
				nome: 'VW Jetta',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/JETA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000715',
				codigoAcronymLocaliza: 'CLTZ',
				codigoModelo: '000715',
				codigoFabricante: 'C',
				nome: 'GM Cruze',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CLTZ.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'H_000021',
				codigoAcronymLocaliza: 'ARZO',
				codigoModelo: '000021',
				codigoFabricante: 'H',
				nome: 'Chery Arrizo 6 Pro',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ARZO.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'EXECUTIVO FAST',
		codigoLocaliza: 'LK',
		codigoInternacional: 'GZAR',
		codigoTipoGrupoVeiculo: 15,
		categoria: 'Fast',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/CRUF.png',
		acessorios: [
			{
				descricao: 'Abre no App',
				codigoAcessorio: 34,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'C_000903',
				codigoAcronymLocaliza: 'CRUF',
				codigoModelo: '000903',
				codigoFabricante: 'C',
				nome: 'GM Cruze Sedan FAST',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CRUF.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'G_000250',
				codigoAcronymLocaliza: 'COLF',
				codigoModelo: '000250',
				codigoFabricante: 'G',
				nome: 'Toyota Corolla GLI FAST',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/COLF.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV ESPECIAL',
		codigoLocaliza: 'LE',
		codigoInternacional: 'XFAR',
		codigoTipoGrupoVeiculo: 7,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/COMP.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: '8_000030',
				codigoAcronymLocaliza: 'COMP',
				codigoModelo: '000030',
				codigoFabricante: '8',
				nome: 'Jeep Compass Longitude',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/COMP.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'G_000296',
				codigoAcronymLocaliza: 'CCRO',
				codigoModelo: '000296',
				codigoFabricante: 'G',
				nome: 'Toyota Corolla Cross XR',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CCRO.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000947',
				codigoAcronymLocaliza: 'TAOS',
				codigoModelo: '000947',
				codigoFabricante: 'B',
				nome: 'VW Taos Highline',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TAOS.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'M_000171',
				codigoAcronymLocaliza: 'ECLI',
				codigoModelo: '000171',
				codigoFabricante: 'M',
				nome: 'Mitsubishi Eclipse Cross',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/ECLI.png',
			},
			{
				blindado: false,
				codigoLocaliza: '1_000150',
				codigoAcronymLocaliza: 'TUCN',
				codigoModelo: '000150',
				codigoFabricante: '1',
				nome: 'Hyundai New Tucson',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TUCN.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'H_000020',
				codigoAcronymLocaliza: 'TIGO',
				codigoModelo: '000020',
				codigoFabricante: 'H',
				nome: 'Chery Tiggo 7 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TIGO.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV ELITE',
		codigoLocaliza: 'GR',
		codigoInternacional: 'XDAR',
		codigoTipoGrupoVeiculo: 7,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/TIGX.png',
		acessorios: [
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Direção Elétrica',
				codigoAcessorio: 29,
			},
			{
				descricao: 'Banco de Couro',
				codigoAcessorio: 26,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 7,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'H_000010',
				codigoAcronymLocaliza: 'TIGX',
				codigoModelo: '000010',
				codigoFabricante: 'H',
				nome: 'Chery Tiggo 8 1.6',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TIGX.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV AUTOMÁTICO A DIESEL',
		codigoLocaliza: 'GD',
		codigoInternacional: 'IFAD',
		codigoTipoGrupoVeiculo: 7,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/RE4D.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Diesel',
				codigoAcessorio: 14,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: '8_000023',
				codigoAcronymLocaliza: 'RE4D',
				codigoModelo: '000023',
				codigoFabricante: '8',
				nome: 'Jeep Renegade 4x4 Diesel',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/RE4D.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV ESPECIAL A DIESEL',
		codigoLocaliza: 'LD',
		codigoInternacional: 'XFAD',
		codigoTipoGrupoVeiculo: 7,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/CO4D.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Diesel',
				codigoAcessorio: 14,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: '8_000031',
				codigoAcronymLocaliza: 'CO4D',
				codigoModelo: '000031',
				codigoFabricante: '8',
				nome: 'Jeep Compass 4x4 Diesel',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/CO4D.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'SUV ELITE A DIESEL',
		codigoLocaliza: 'SV',
		codigoInternacional: 'PFAD',
		codigoTipoGrupoVeiculo: 7,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/PJRS.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 7,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'M_000181',
				codigoAcronymLocaliza: 'PJRS',
				codigoModelo: '000181',
				codigoFabricante: 'M',
				nome: 'Mitsubishi Pajero 2.4 Diesel',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PJRS.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'EXECUTIVO ELETRICO',
		codigoLocaliza: 'FE',
		codigoInternacional: 'LDAE',
		codigoTipoGrupoVeiculo: 9,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/BOLT.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 1,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'C_001003',
				codigoAcronymLocaliza: 'BOLT',
				codigoModelo: '001003',
				codigoFabricante: 'C',
				nome: 'GM Bolt Premier Elétrico',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/BOLT.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'LOCALIZA PRIME',
		codigoLocaliza: 'LP',
		codigoInternacional: 'PDAR',
		codigoTipoGrupoVeiculo: 10,
		categoria: 'Passeio',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/MCAV.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Banco de Couro',
				codigoAcessorio: 26,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
			{
				descricao: 'Direção Elétrica',
				codigoAcessorio: 29,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'F_000227',
				codigoAcronymLocaliza: 'MCAV',
				codigoModelo: '000227',
				codigoFabricante: 'F',
				nome: 'Mercedes C180 Avantgarde',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/MCAV.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'EXECUTIVO BLINDADO',
		codigoLocaliza: 'T',
		codigoInternacional: 'PZAR',
		categoria: 'Blindado',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/AUDB.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 3,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: true,
				codigoLocaliza: 'W_000177',
				codigoAcronymLocaliza: 'AUDB',
				codigoModelo: '000177',
				codigoFabricante: 'W',
				nome: 'Audi A4 TFSI',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/AUDB.png',
			},
			{
				blindado: true,
				codigoLocaliza: 'D_000395',
				codigoAcronymLocaliza: 'FUSB',
				codigoModelo: '000395',
				codigoFabricante: 'D',
				nome: 'Novo Ford Fusion',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/FUSB.png',
			},
			{
				blindado: true,
				codigoLocaliza: 'G_000290',
				codigoAcronymLocaliza: 'COLB',
				codigoModelo: '000290',
				codigoFabricante: 'G',
				nome: 'Toyota Corolla',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/COLB.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'MINIVAN',
		codigoLocaliza: 'R',
		codigoInternacional: 'MVMR',
		codigoTipoGrupoVeiculo: 8,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/DBLO.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: '3 portas',
				codigoAcessorio: 11,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 7,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_000410',
				codigoAcronymLocaliza: 'DBLO',
				codigoModelo: '000410',
				codigoFabricante: 'A',
				nome: 'Fiat Doblo 1.8',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/DBLO.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'MINIVAN ESPECIAL',
		codigoLocaliza: 'RX',
		codigoInternacional: 'MVAR',
		codigoTipoGrupoVeiculo: 8,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/SPIX.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 2,
			quantidadeMalasPequenas: 2,
			quantidadePassageiros: 7,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'C_000755',
				codigoAcronymLocaliza: 'SPIX',
				codigoModelo: '000755',
				codigoFabricante: 'C',
				nome: 'GM Spin 1.8',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/SPIX.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'PICK-UP COM AR',
		codigoLocaliza: 'V',
		codigoInternacional: 'MPMR',
		codigoTipoGrupoVeiculo: 12,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/STDA.png',
		acessorios: [
			{
				descricao: '2 portas',
				codigoAcessorio: 1,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 705.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 2,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_000465',
				codigoAcronymLocaliza: 'STDA',
				codigoModelo: '000465',
				codigoFabricante: 'A',
				nome: 'Fiat Strada 1.4',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/STDA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'B_000522',
				codigoAcronymLocaliza: 'SAVE',
				codigoModelo: '000522',
				codigoFabricante: 'B',
				nome: 'VW Saveiro 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/SAVE.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'C_000584',
				codigoAcronymLocaliza: 'MONT',
				codigoModelo: '000584',
				codigoFabricante: 'C',
				nome: 'GM Montana 1.4',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/MONT.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'PICK-UP COM AR PLUS',
		codigoLocaliza: 'VP',
		codigoInternacional: 'NPMR',
		codigoTipoGrupoVeiculo: 12,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/STCD.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 720.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_001164',
				codigoAcronymLocaliza: 'STCD',
				codigoModelo: '001164',
				codigoFabricante: 'A',
				nome: 'Fiat Strada Cabine Dupla 1.3',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/STCD.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'PICK-UP DE LUXO',
		codigoLocaliza: 'NX',
		codigoInternacional: 'PPAR',
		codigoTipoGrupoVeiculo: 12,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/TORA.png',
		acessorios: [
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Trava elétrica',
				codigoAcessorio: 5,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'Automático',
				codigoAcessorio: 15,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
			{
				descricao: 'Direção Elétrica',
				codigoAcessorio: 29,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 650.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_001063',
				codigoAcronymLocaliza: 'TORA',
				codigoModelo: '001063',
				codigoFabricante: 'A',
				nome: 'Fiat Toro 1.8',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TORA.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'R_000349',
				codigoAcronymLocaliza: 'OROH',
				codigoModelo: '000349',
				codigoFabricante: 'R',
				nome: 'Renault Duster Oroch 2.0',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/OROH.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'FURGÃO',
		codigoLocaliza: 'U',
		codigoInternacional: 'MKMN',
		codigoTipoGrupoVeiculo: 16,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/FIFO.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 620.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 2,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_001083',
				codigoAcronymLocaliza: 'FIFO',
				codigoModelo: '001083',
				codigoFabricante: 'A',
				nome: 'Fiat Fiorino 1.4',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/FIFO.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'O_000125',
				codigoAcronymLocaliza: 'PATN',
				codigoModelo: '000125',
				codigoFabricante: 'O',
				nome: 'Peugeot Partner Furgão 1.6',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/PATN.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'FURGÃO ESPECIAL',
		codigoLocaliza: 'US',
		codigoInternacional: 'XPMR',
		codigoTipoGrupoVeiculo: 16,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/BOXR.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Vidro elétrico',
				codigoAcessorio: 4,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Diesel',
				codigoAcessorio: 14,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 999.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 2,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'O_000236',
				codigoAcronymLocaliza: 'BOXR',
				codigoModelo: '000236',
				codigoFabricante: 'O',
				nome: 'Peugeot Boxer Cargo 2.0 Turbo',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/BOXR.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'T_000168',
				codigoAcronymLocaliza: 'JUMP',
				codigoModelo: '000168',
				codigoFabricante: 'T',
				nome: 'Citroen Jumper Cargo 2.0 Turbo',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/JUMP.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'A_001116',
				codigoAcronymLocaliza: 'DUCA',
				codigoModelo: '001116',
				codigoFabricante: 'A',
				nome: 'Fiat Ducato Maxicargo 2.3',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/DUCA.png',
			},
		],
		destaque: false,
	},
	{
		nome: '4x4 ESPECIAL',
		codigoLocaliza: 'P',
		codigoInternacional: 'FQMR',
		codigoTipoGrupoVeiculo: 13,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/S10X.png',
		acessorios: [
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Cabine Dupla',
				codigoAcessorio: 12,
			},
			{
				descricao: 'Tração 4x4',
				codigoAcessorio: 13,
			},
			{
				descricao: '4 portas',
				codigoAcessorio: 2,
			},
			{
				descricao: 'Diesel',
				codigoAcessorio: 14,
			},
			{
				descricao: 'Air bag',
				codigoAcessorio: 6,
			},
			{
				descricao: 'ABS',
				codigoAcessorio: 28,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 999.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'C_000448',
				codigoAcronymLocaliza: 'S10X',
				codigoModelo: '000448',
				codigoFabricante: 'C',
				nome: 'GM S10 2.8',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/S10X.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'G_000197',
				codigoAcronymLocaliza: 'TOYH',
				codigoModelo: '000197',
				codigoFabricante: 'G',
				nome: 'Toyota Hilux 2.8',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TOYH.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'U_000176',
				codigoAcronymLocaliza: 'FRON',
				codigoModelo: '000176',
				codigoFabricante: 'U',
				nome: 'Nissan Frontier 2.3',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/FRON.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'D_000185',
				codigoAcronymLocaliza: 'RANG',
				codigoModelo: '000185',
				codigoFabricante: 'D',
				nome: 'Ford Ranger 2.2',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/RANG.png',
			},
			{
				blindado: false,
				codigoLocaliza: 'M_000200',
				codigoAcronymLocaliza: 'L200',
				codigoModelo: '000200',
				codigoFabricante: 'M',
				nome: 'Mitsubishi L200 Triton 2.4',
				padraoGrupo: false,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/L200.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'VAN',
		codigoLocaliza: 'J',
		codigoInternacional: 'FVMR',
		codigoTipoGrupoVeiculo: 16,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/DUCM.png',
		acessorios: [
			{
				descricao: 'Diesel',
				codigoAcessorio: 14,
			},
			{
				descricao: 'Dir. Hidráulica',
				codigoAcessorio: 9,
			},
			{
				descricao: 'Ar-condicionado',
				codigoAcessorio: 3,
			},
		],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 0.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 0,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_000338',
				codigoAcronymLocaliza: 'DUCM',
				codigoModelo: '000338',
				codigoFabricante: 'A',
				nome: 'Van',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/DUCM.png',
			},
		],
		destaque: false,
	},
	{
		nome: 'PICK-UP LUXO 4X4 DIESEL',
		codigoLocaliza: 'VD',
		codigoInternacional: 'PPAD',
		codigoTipoGrupoVeiculo: 12,
		categoria: 'Utilitario',
		imagemPadrao: 'https://www.localiza.com/brasil-site/geral/Frota/TO4D.png',
		acessorios: [],
		capacidade: {
			capacidadeLitros: 0.0,
			capacidadeQuilogramas: 650.0,
			quantidadeMalasGrandes: 0,
			quantidadeMalasPequenas: 0,
			quantidadePassageiros: 5,
		},
		veiculos: [
			{
				blindado: false,
				codigoLocaliza: 'A_001066',
				codigoAcronymLocaliza: 'TO4D',
				codigoModelo: '001066',
				codigoFabricante: 'A',
				nome: 'Fiat Toro 2.0 Diesel 4X4',
				padraoGrupo: true,
				urlImagem: 'https://www.localiza.com/brasil-site/geral/Frota/TO4D.png',
			},
		],
		destaque: false,
	},
];
